<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="proectCalendar" nsURI="http://www.example.org/proectCalendar"
    nsPrefix="proectCalendar">
  <eClassifiers xsi:type="ecore:EClass" name="Vcalendar">
    <eOperations name="accept">
      <eParameters name="visitor" eType="#//VcalendarVisitor"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="prodid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="instruction" upperBound="-1"
        eType="#//Instruction" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Vtodo">
    <eOperations name="accept">
      <eParameters name="visitor" eType="#//VcalendarVisitor"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="alarm" upperBound="-1"
        eType="#//Valarm" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dtstamp" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uid" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="class" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="completed" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="created" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Valarm">
    <eOperations name="accept">
      <eParameters name="visitor" eType="#//VcalendarVisitor"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="action" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="trigger" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="duration" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="repeat" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShort"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Vjournal">
    <eOperations name="accept">
      <eParameters name="visitor" eType="#//VcalendarVisitor"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dtstamp" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uid" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dtstart" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="summuary" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Vevent">
    <eOperations name="accept">
      <eParameters name="visitor" eType="#//VcalendarVisitor"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="alarm" upperBound="-1"
        eType="#//Valarm" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uid" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dtstamp" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dtstart" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dtend" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="duration" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Vtimezone">
    <eOperations name="accept">
      <eParameters name="visitor" eType="#//VcalendarVisitor"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="standard" upperBound="-1"
        eType="#//Standard" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tzid" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="last_mod" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tzurl" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="daylight" upperBound="-1"
        eType="#//Daylight" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Freebusy">
    <eOperations name="accept">
      <eParameters name="visitor" eType="#//VcalendarVisitor"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uid" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dtstamp" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dtstart" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dtend" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attendee" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="organizer" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Standard">
    <eOperations name="accept">
      <eParameters name="visitor" eType="#//VcalendarVisitor"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Daylight">
    <eOperations name="accept">
      <eParameters name="visitor" eType="#//VcalendarVisitor"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Instruction">
    <eOperations name="accept">
      <eParameters name="visitor" eType="#//VcalendarVisitor"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="todo" upperBound="-1" eType="#//Vtodo"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="journal" upperBound="-1"
        eType="#//Vjournal" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="event" upperBound="-1"
        eType="#//Vevent" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="timezone" upperBound="-1"
        eType="#//Vtimezone" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="freebusy" upperBound="-1"
        eType="#//Freebusy" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VcalendarVisitor" abstract="true">
    <eOperations name="visit">
      <eParameters name="vcalendar" eType="#//Vcalendar"/>
    </eOperations>
    <eOperations name="visit">
      <eParameters name="vtodo" eType="#//Vtodo"/>
    </eOperations>
    <eOperations name="visit">
      <eParameters name="vjournal" eType="#//Vjournal"/>
    </eOperations>
    <eOperations name="visit">
      <eParameters name="vevent" eType="#//Vevent"/>
    </eOperations>
    <eOperations name="visit">
      <eParameters name="vtimezone" eType="#//Vtimezone"/>
    </eOperations>
    <eOperations name="visit">
      <eParameters name="freebusy" eType="#//Freebusy"/>
    </eOperations>
  </eClassifiers>
</ecore:EPackage>
